/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module FourBitAdder(a, b, cin, sum, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  input a;
  input b;
  input cin;
  output cout;
  output sum;
  wire w1;
  wire w2;
  wire w3;
  assign _00_ = a & b;
  assign _01_ = a & cin;
  assign _02_ = b & cin;
  assign _03_ = w1 | w2;
  assign _04_ = _03_ | w3;
  assign _05_ = a ^ b;
  assign _06_ = _05_ ^ cin;
  assign sum = _06_;
  assign w1 = _00_;
  assign w2 = _01_;
  assign w3 = _02_;
  assign cout = _04_;
endmodule
